
MSBUILD=C:\Windows\Microsoft.NET\Framework\v4.0.30319\MSBuild.exe
#MSBUILD=C:/Windows/Microsoft.NET/Framework/v4.0.30319/MSBuild.exe

#BIN = ../../bin_tools/NuBuild
#	
#NUBUILD_SOURCES = $(wildcard NuBuild/*.cs) NuBuild/NuBuild.csproj
#
#all: $(BIN)/NuBuild.exe
#
#$(BIN)/NuBuild.exe: $(NUBUILD_SOURCES) NuBuild.sln
#	$(MSBUILD) NuBuild.sln

all: me

me: 
	echo hi
	$(MSBUILD) NuBuild.sln

